# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image
import filer_addons.filer_gui.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerTestInlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('filer_file', filer_addons.filer_gui.fields.FilerFileField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_filerinlinetest', to='filer.File')),
                ('filer_file_ugly', filer.fields.file.FilerFileField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_ugly_filerinlinetest', to='filer.File')),
                ('filer_image', filer_addons.filer_gui.fields.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_filerinlinetest', to='filer.Image')),
                ('filer_image_ugly', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_ugly_filerinlinetest', to='filer.Image')),
                ('filer_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.FilerTest')),
            ],
        ),
    ]
