# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20170705_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filertest',
            name='parent',
        ),
        migrations.AlterField(
            model_name='filertest',
            name='filer_file_raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
