# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('testapp', '0004_auto_20170705_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerUglyFileInlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('filer_file_ugly', filer.fields.file.FilerFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File')),
                ('filer_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.FilerTest')),
            ],
        ),
        migrations.CreateModel(
            name='FilerUglyImageInlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('filer_image_ugly', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image')),
                ('filer_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.FilerTest')),
            ],
        ),
        migrations.RemoveField(
            model_name='filertestinlinemodel',
            name='filer_file',
        ),
        migrations.RemoveField(
            model_name='filertestinlinemodel',
            name='filer_file_ugly',
        ),
        migrations.RemoveField(
            model_name='filertestinlinemodel',
            name='filer_image',
        ),
        migrations.RemoveField(
            model_name='filertestinlinemodel',
            name='filer_image_ugly',
        ),
        migrations.RemoveField(
            model_name='filertestinlinemodel',
            name='filer_test',
        ),
        migrations.DeleteModel(
            name='FilerTestInlineModel',
        ),
    ]
