# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20171107_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filertest',
            name='filer_file_ugly_2',
        ),
    ]
