# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_remove_filertest_filer_file_ugly_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileruglytest',
            name='filer_file_ugly',
        ),
        migrations.RemoveField(
            model_name='fileruglytest',
            name='filer_image_ugly',
        ),
        migrations.DeleteModel(
            name='FilerUglyTest',
        ),
    ]
