# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer_addons.filer_gui.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('testapp', '0010_auto_20171107_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerNewFileInlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('filer_file', filer_addons.filer_gui.fields.FilerFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File')),
                ('filer_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.FilerTest')),
            ],
        ),
        migrations.CreateModel(
            name='FilerNewImageInlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('filer_image', filer_addons.filer_gui.fields.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
                ('filer_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.FilerTest')),
            ],
        ),
    ]
