# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image
import filer_addons.filer_gui.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('testapp', '0011_filernewfileinlinemodel_filernewimageinlinemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerNewFieldTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('filer_file', filer_addons.filer_gui.fields.FilerFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_filertest', to='filer.File')),
                ('filer_file_raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File')),
                ('filer_image', filer_addons.filer_gui.fields.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_filertest', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilerOriginalFieldTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('filer_file_original', filer.fields.file.FilerFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_original_filertest', to='filer.File')),
                ('filer_file_raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File')),
                ('filer_image_original', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_original_filertest', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='FilerUglyFileInlineModel',
            new_name='FilerOriginalFileInlineModel',
        ),
        migrations.RenameModel(
            old_name='FilerUglyImageInlineModel',
            new_name='FilerOriginalImageInlineModel',
        ),
        migrations.RemoveField(
            model_name='filertest',
            name='filer_file',
        ),
        migrations.RemoveField(
            model_name='filertest',
            name='filer_file_raw',
        ),
        migrations.RemoveField(
            model_name='filertest',
            name='filer_file_ugly',
        ),
        migrations.RemoveField(
            model_name='filertest',
            name='filer_image',
        ),
        migrations.RemoveField(
            model_name='filertest',
            name='filer_image_ugly',
        ),
        migrations.RenameField(
            model_name='fileroriginalfileinlinemodel',
            old_name='filer_file_ugly',
            new_name='filer_file_original',
        ),
        migrations.RenameField(
            model_name='fileroriginalimageinlinemodel',
            old_name='filer_image_ugly',
            new_name='filer_image_original',
        ),
        migrations.AlterField(
            model_name='filernewfileinlinemodel',
            name='filer_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.FilerNewFieldTest'),
        ),
        migrations.AlterField(
            model_name='filernewimageinlinemodel',
            name='filer_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.FilerNewFieldTest'),
        ),
        migrations.AlterField(
            model_name='fileroriginalfileinlinemodel',
            name='filer_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.FilerOriginalFieldTest'),
        ),
        migrations.AlterField(
            model_name='fileroriginalimageinlinemodel',
            name='filer_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.FilerOriginalFieldTest'),
        ),
        migrations.DeleteModel(
            name='FilerTest',
        ),
    ]
