# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('filer_gui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerGuiFolder',
            fields=[
            ],
            options={
                'abstract': False,
                'proxy': True,
            },
            bases=('filer.folder',),
        ),
    ]
