# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer_gui', '0002_filerguifolder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilerGuiFolder',
        ),
    ]
